#+Title: Emacs literate configuration
#+Author: Błażej Nowiński
#+Description: A configuration for writing academic notes and more.
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+Startup: showeverything
#+Options: toc:2

* Table Of Contents :toc:
- [[#resources][Resources]]
  - [[#manual][Manual]]
  - [[#books][Books]]
- [[#core-setup--performance][Core Setup & Performance]]
  - [[#startup][Startup]]
  - [[#package-manager][Package manager]]
  - [[#emacs-settings][Emacs settings]]
  - [[#custom-functions--global-keybindings][Custom functions & Global keybindings]]
- [[#appearance][Appearance]]
  - [[#theme][Theme]]
  - [[#doom-modeline][Doom Modeline]]
  - [[#nerd-icons][Nerd Icons]]
- [[#core-packages][Core packages]]
  - [[#navigation-avy--ace-link--ace-window][Navigation (avy + ace-link + ace-window)]]
  - [[#better-help-helpful--which-key][Better Help (Helpful + Which-key)]]
  - [[#minibuffer-vertico--marginalia][Minibuffer (Vertico + Marginalia)]]
  - [[#completion-corfu--cape--orderless][Completion (Corfu + Cape + Orderless)]]
  - [[#eat-emulate-a-terminal][Eat (Emulate A Terminal)]]
  - [[#version-control-magit--diff-hl][Version Control (Magit + Diff-hl)]]
  - [[#miscellaneous-undos-todos--generally-prettify][Miscellaneous (undos todos & generally prettify)]]
  - [[#consult][Consult]]
- [[#file-management--opening][File management & opening]]
  - [[#dired][Dired]]
  - [[#viewing-files--externally][Viewing files (& externally)]]
- [[#writing][Writing]]
  - [[#org-mode][Org Mode]]
  - [[#text-mode][text mode]]
  - [[#emacs-writing-studio-variables-autoload--executables-check][Emacs writing studio variables autoload & executables check]]
  - [[#notetaking-org--denote--consult][Notetaking (org + denote + consult)]]
  - [[#bibliography][Bibliography]]
  - [[#spell-check-sideline-flymake][Spell check (Sideline-flymake)]]
  - [[#export][Export]]
- [[#trying-out---packages][Trying out - packages]]
  - [[#embark][Embark]]
- [[#coding][Coding]]
  - [[#projectile][Projectile]]
  - [[#lsp-eglot--mason][LSP (Eglot + Mason)]]
  - [[#tree-sitter][Tree-Sitter]]
  - [[#snippets-yasnippet--snippy][Snippets (Yasnippet + Snippy)]]

* Resources
It is *recommended* to configure it from the *init.org* file.
Kickstart.emacs is a starting point for your own configuration.
MiniApollo

First I recommend starting with the Emacs tutorial with the following
keybinding: C-h t Or running the command with M-x: help-with-tutorial

Test ./

** Manual
Everything under C-h is used for help keybindings.

Using the following keybind: C-h C-h Or running the following command
M-x: help-for-help

The most used commands for me are:
- C-h v Describe variable
- C-h f Describe function
- C-h k Describe key

Other also really useful ones:
- C-h i Show all installed manuals
- C-h r Emacs manual
- C-h a Search for commands (see also M-x: Apropos)
- C-h m Show help for current major and minor modes

For more about info-mode: C-h f: info-mode

Basic navigation:
- d key: Go back to the top-level Info Directory.
- u key: Go up to the parent node in the document's hierarchy.
- n key: for next node in the current manual.
- p key: for previous node in the current manual.

*Note:* A Node is essentially a specific section or topic, much like a
chapter or subsection in a book.

When you are browsing through the Emacs manual you can easily search
with:
- i key: for specific subjects in the current manual.
- g key: for nodes (sections).
- m key: for menu items within the current Info buffer.
- s key: for regular expression patterns (like words) within the
  current Info buffer.

Using goto-node:
- Specify a Manual: If you want to search within a particular manual,
  place its name in parentheses like (emacs).
- After that tell where you want to go in that manual. For example
  (emacs)Top, (emacs)specific section.
- If you don't type a manual name, goto-node will search the currently
  opened manual.

** Books
basic lisp
https://learnxinyminutes.com/elisp/
advanced lisp
https://www.gnu.org/software/emacs/manual/html_node/eintr/

* Core Setup & Performance
These are essential settings and small tweaks that must load before
any packages. They impact the entire configuration, skipping these
could result in significantly slower configuration and potential
breakage of your setup.

** Startup
Gotta go fast.

*** Startup Performance
Core performance tweaks moved to early-init.el
See: [[https://github.com/doomemacs/doomemacs/issues/310][Why is doom emacs so fast?]]

*** Lexical-bindings
Gives better performance, lexical closures, and code safety, allowing
local variables to remain truly local.
#+begin_src emacs-lisp
    ;; -*- lexical-binding: t; -*-
#+end_src

*** Early-Init.el
This file is loaded before anything else. Most of the performance
tweaks are there. We can configure things before the GUI or other
packages are loaded.

*** Auto-tangle Configuration file
Auto-Tangle Org configuration file for better startup times, it
refreshes the package-quickstart file. We'll cover package quickstart
in the package manager section later.

If you like to auto tangle an Org file, don't forget to add the
following line to the top of your Org document: (#+PROPERTY:
header-args:emacs-lisp :tangle ./init.el :mkdirp yes)

*Remember*, if this code can't be loaded (errors before this code), the
init.el file won't update on change! To fix this, you need to find
this file (C-x C-f), fix the error and press C-c C-v t to tangle it
manually.

This snippet adds a hook to org-mode buffers so that
start/org-babel-tangle-config gets executed each time such a buffer
gets saved. This function checks to see if the file being saved is the
init.org file you’re looking at right now, and if so, automatically
exports the configuration here to the associated output files.
#+begin_src emacs-lisp
    (defun baej/org-babel-tangle-config ()
      "Automatically tangle our init.org config file and refresh package-quickstart when we save it. Credit to Emacs From Scratch for this one!"
      (interactive)
      (when (string-equal (file-name-directory (buffer-file-name))
                          (expand-file-name user-emacs-directory))
        ;; Dynamic scoping to the rescue
        (let ((org-confirm-babel-evaluate nil))
          (org-babel-tangle)
          (package-quickstart-refresh)
          )))

    (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'baej/org-babel-tangle-config)))
#+end_src

*** Show startup time
#+begin_src emacs-lisp
    (defun start/display-startup-time ()
      (interactive)
      (message "Emacs loaded in %s with %d garbage collections."
               (format "%.2f seconds"
                       (float-time
                        (time-subtract after-init-time before-init-time)))
               gcs-done))

    (add-hook 'emacs-startup-hook #'start/display-startup-time)
#+end_src

*** (optional) Multi File Example
**** Adding the lisp directory to load-path
Adds the lisp directory to Emacs's load path to search for elisp files.
This is necessary because Emacs does not search the entire user-emacs-directory.
The directory name can be anything, just add it to the load-path.
#+begin_src emacs-lisp
    ;; (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
#+end_src

**** Using the file
And now we can use everything from that file.
#+begin_src emacs-lisp
    ;; (start/hello)
#+end_src

**** Sourcing the files
To use the elisp files we need to load it.
Notes:
- Don't forget the file and the provide name needs to be the same.
- When naming elisp files, functions, it is recommended to use a group name (e.g. init-, start- or any custom name), so it does not get mixed up with other names, functions.
#+begin_src emacs-lisp
    ;; (require 'start-multiFileExample)
#+end_src

*** Startup timer
Esup (Emacs Start Up Profiler)
Benchmark Emacs Startup time: M-x esup

#+begin_src emacs-lisp
    (use-package esup
      :defer
      :custom
      (esup-depth 0))
#+end_src

** Package manager
We use the default built in package manager package.el.

Alternative package managers (straight.el, elpaca, etc.) are useful if
you want:
- Faster package installation.
- Lock file support for recovery if something goes wrong.
- Packages that are cloned as Git (or other) repositories, not as
  opaque tarballs.
- Better UI
- Async support

If you are interested in using other package managers, check out their
git repositories.  To learn more about why something like [[https://github.com/doomemacs/doomemacs/blob/master/docs/faq.org#why-does-doom-use-straightel-and-not-packageel][doomemacs
uses]] straight.el not package.el.

In my experience Package.el is not slow and gets the job done.

To update/upgrade packages, use the package-upgrade-all command.
Package.el has a UI. Check it out with M-x list-packages.

*** Use-package
A macro that allows you to isolate package configuration in your
.emacs file in a way that is both performance-oriented and, well,
tidy.  We use it because it makes package configuration really easy.

With Emacs 29 use-package is now built-in.

This code eliminates the need to type :ensure t for each package
download.  Instead, you'll only need to use :ensure nil when you want
to explicitly prevent a package from being downloaded.
#+begin_src emacs-lisp
  (use-package use-package
    :custom
    (use-package-always-ensure t)
    (package-native-compile t)
    (warning-minimum-level :emergency))
#+end_src

**** Most used parts of use-package
Here is some notes on what each use-package keyword does.
For more check out the use-package documentation to see how powerful it is:
C-h i: g for goto-node: Type (use-package)Top

This code block is not tangled, it is just an example.
#+begin_src emacs-lisp :tangle no
  ;; Configure the 'foo' package
  ;; You can also use (use-package emacs) to customize Emacs with use-package.
  (use-package foo
    :init (message "Before")    ;; execute code Before a package is loaded.
    :config (message "After")   ;; execute code After a package is loaded.
    :custom (foovar t)          ;; Customization of package custom variables same as setq.
    :ensure t                   ;; Ensure the package is installed if it's not already.

    ;; These are also used for lazy loading.
    ;; Don't load the package until these are not true.
    :bind ("C-." . myfunc)      ;; Defer package loading until keybindings are invoked.
    :after (mypackage)          ;; Load package after specified packages have been loaded.
    ;; If you don't know what a hook is:
    ;; C-h i: g for goto-node: Type (emacs)Hooks
    :hook (myhook . myfunc)     ;; Add functions to specified hooks when the package is loaded.

    :command (bar)              ;; Define commands provided by the package to be lazy-loaded.
    :defer t                    ;; Only load this package if it's explicitly needed or a command/hook associated with it is called.
    ;; Install package with package.el from source.
    :vc (:url "<You git repo url>"
              :branch "main"
              :rev :newest) ;; Use latest commit
    )
#+end_src

*** Setting package repositories
Like Linux distributions, Emacs uses repositories to manage its packages.
#+begin_src emacs-lisp
  (setq package-archives '(("melpa" . "https://melpa.org/packages/") ;; Sets default package repositories
                           ("elpa" . "https://elpa.gnu.org/packages/")
                           ("nongnu" . "https://elpa.nongnu.org/nongnu/"))) ;; For Eat Terminal
#+end_src

*** Package quickstart
Improves startup times by allowing Emacs to precompute and generate a
single, large autoload file.  Instead of re-computing them on every
startup.

The larger your configuration, the more it will be felt at startup.

However, if you enable this, you'll need to manually run the
package-quickstart-refresh command whenever your package activations
change, such as when you modify the package-load-list value.  We put
it inside Auto-tangle hook so when we save this file it runs it
automatically.

As I tested, it makes startup about 0.1 seconds faster.  Avg:
- Off: 0.66 sec
- On: 0.59 sec

Package quickstart only works with package.el.  If you plan to use a
different package manager, remember to remove this section and the
package-quickstart-refresh line in the Auto-tangle hook.
#+begin_src emacs-lisp
  (setq package-quickstart t) ;; For blazingly fast startup times, this line makes startup miles faster
#+end_src

*** Package Async
Simple library for asynchronous processing in Emacs.
Makes package installation about 30 sec faster.
Only works with package.el.
#+begin_src emacs-lisp
  (use-package async
    :defer
    :custom
    (dired-async-mode t)
    (async-bytecomp-package-mode t)
    (async-bytecomp-allowed-packages '(all))
    (async-package-do-action t))
#+end_src

** Emacs settings
#+begin_src emacs-lisp
  (use-package emacs
    :custom
    ;; Still needed for terminals
    (menu-bar-mode nil)         ;; Disable the menu bar
    (scroll-bar-mode nil)       ;; Disable the scroll bar
    (tool-bar-mode nil)         ;; Disable the tool bar

    (inhibit-startup-screen t)  ;; Disable welcome screen
    (initial-major-mode 'org-mode)        ;; Scratch buffer org mode
    (setq initial-scratch-message (concat ""))

    (delete-selection-mode t)   ;; Select text and delete it by typing.
    (electric-indent-mode nil)  ;; Turn off the weird indenting that
                                ;; Emacs does by default.
    (electric-pair-mode t)      ;; Turns on automatic parens pairing

    (blink-cursor-mode nil)     ;; Don't blink cursor
    (global-auto-revert-mode t) ;; Automatically reload file and show changes if the file has changed
    (use-short-answers t)   ;; Since Emacs 29, `yes-or-no-p' will use 'y-or-n-p'

    ;;(dired-kill-when-opening-new-dired-buffer t) ;; Dired don't create new buffer
    ;;(recentf-mode t) ;; Enable recent file mode
    (when (display-graphic-p)(context-menu-mode t)) ;; Right-click menu

    (global-visual-line-mode t)           ;; Enable line wrapping (NOTE: breaks vundo)

    ;;(global-display-line-numbers-mode t)  ;; Display line numbers
    ;;(display-line-numbers-type 'relative) ;; Relative line numbers
    (global-hl-line-mode t)               ;; Highlight current line
    (fill-column 70)

    (native-comp-async-report-warnings-errors 'silent) ;; Don't show native comp errors
    (warning-minimum-level :error) ;; Only show errors in warnings buffer

    (mouse-wheel-progressive-speed nil) ;; Disable progressive speed when scrolling
    (scroll-conservatively 10) ;; Smooth scrolling
    ;; (scroll-margin 8)

    ;; (pixel-scroll-precision-mode t) ;; Precise pixel scrolling. i.e. smooth scrolling (GUI only)
    ;; (pixel-scroll-precision-use-momentum nil)

    (indent-tabs-mode nil) ;; Only use spaces for indentation
    (tab-width 2)
    (sgml-basic-offset 4) ;; Set Html mode indentation to 4
    (c-ts-mode-indent-offset 4) ;; Fix weird indentation in c-ts (C, C++)
    (go-ts-mode-indent-offset 4) ;; Fix weird indentation in go-ts

    ;; (display-fill-column-indicator-column 80) ;; Set line length indicator to 80 characters
    (whitespace-style '(face tabs tab-mark trailing))
    (winner-mode 1)

    (make-backup-files nil) ;; Stop creating ~ backup files
    (auto-save-default nil) ;; Stop creating # auto save files
    (delete-by-moving-to-trash t)
    :hook
    (prog-mode . hs-minor-mode) ;; Enable folding hide/show globally
    ;; (prog-mode . display-fill-column-indicator-mode) ;; Display line length indicator
    (prog-mode . whitespace-mode)
    (text-mode . auto-fill-mode)
    :config
    ;; Move customization variables to a separate file and load it, avoid filling up init.el with unnecessary variables
    (setq custom-file (locate-user-emacs-file "custom-vars.el"))
    (load custom-file 'noerror 'nomessage)
    :bind (
           ([escape] . keyboard-escape-quit) ;; Makes Escape quit prompts (Minibuffer Escape)
           ;; Zooming In/Out
           ("C-+" . text-scale-increase)
           ("C--" . text-scale-decrease)
           ("<C-wheel-up>" . text-scale-increase)
           ("<C-wheel-down>" . text-scale-decrease)
           ))
#+end_src

#+RESULTS:
: text-scale-decrease

** Custom functions & Global keybindings
If you want to use the built in methods I recommend using these ones:

This code block is not tangled, it is just an example.
#+begin_src emacs-lisp :tangle no
    (define-key KEYMAP KEY DEF)
    (global-set-key KEY COMMAND)
    (use-package :bind (  ))
#+end_src
To read more about using the built in methods, check out this awesome article from [[https://www.masteringemacs.org/article/mastering-key-bindings-emacs][masteringemacs]].

*** Half-page jumps
Vim-inspired half-page jumps with centering.
#+begin_src emacs-lisp
  (defun baej-scroll-half-page-down-and-center ()
    (interactive)
    (vertical-motion (/ (window-body-height) 2))
    (recenter))

  (defun baej-scroll-half-page-up-and-center ()
    (interactive)
    (vertical-motion (- (/ (window-body-height) 2)))
    (recenter))

  (defun baej-consult-ripgrep-docs ()
         (interactive)
         (require 'consult)
         (consult-ripgrep "/home/baej/docs"))

  (defun baej-consult-fd-docs ()
         (interactive)
         (require 'consult)
         (consult-fd "/home/baej/docs"))

  (global-set-key (kbd "C-v") #'baej-scroll-half-page-down-and-center)
  (global-set-key (kbd "M-v") #'baej-scroll-half-page-up-and-center)
#+end_src

*** Open literate org config
For convenience cuz its wip.
#+begin_src emacs-lisp
(defun baej-open-init-file ()
  "Open init.org configuration file"
  (interactive)
  (find-file "~/.config/emacs/init.org"))

(global-set-key (kbd "C-c i") 'baej-open-init-file)
#+end_src

*** Reload init.el file
#+begin_src emacs-lisp
(defun baej-reload-config ()
  "Reload init.el configuration file"
  (interactive)
  (load-file "~/.config/emacs/init.el"))
(global-set-key (kbd "C-c r") 'baej-reload-config)
#+end_src

*** Customising viariables
#+begin_src emacs-lisp
  (keymap-global-set "C-c w v" 'customize-variable)
  (setq-default custom-file (expand-file-name
  			     "custom.el"
  			     user-emacs-directory))
  (load custom-file :no-error-if-file-is-missing)
#+end_src

* Appearance
Set fonts in the early-init.el file
** Theme
*** Set Theme
Normal way of doing this.
Set gruvbox theme, if you want some themes try out doom-themes.
Use consult-theme to easily try out themes (*Epilepsy* Warning).
#+begin_src emacs-lisp :tangle no
    (use-package gruvbox-theme
      :config
      (setq gruvbox-bold-constructs t)
      (load-theme 'gruvbox-dark-hard t)) ;; We need to add t to trust this package
#+end_src
*** Darkman & Gruvbox (Auto-Theme)
Integration with system service: darkman, with darkman.el package.
It loads the gruvbox theme but doesn't set it.
Darkman is responsible for reading DBUS and sets the theme according to
system configuration.
#+begin_src emacs-lisp
    (use-package gruvbox-theme
      :config
      (setq gruvbox-bold-constructs t))
    (use-package darkman
      :after gruvbox-theme
      :config
      (setq darkman-themes '(:light gruvbox-light-hard :dark gruvbox-dark-hard))
      (defadvice darkman-set (before no-theme-stacking activate)
        "Disable the previous theme before loading a new one."
        (mapc #'disable-theme custom-enabled-themes))
      (if (daemonp)
          (progn
            (add-hook 'server-after-make-frame-hook #'darkman-mode)
            (advice-add 'darkman-mode
                        :after
                        (lambda ()
                          (remove-hook 'server-after-make-frame-hook
                                       #'darkman-mode))))
        (darkman-mode 1)))
#+end_src
*** Transparency
With Emacs version 29, true transparency has been added.
#+begin_src emacs-lisp :tangle no
    (add-to-list 'default-frame-alist '(alpha-background . 90)) ;; For all new frames henceforth
    ;; Transparency in terminal
     (defun start/tui-enable-transparency ()
       (unless (display-graphic-p (selected-frame))
         (set-face-background 'default "unspecified-bg" (selected-frame))))
     (add-hook 'window-setup-hook 'start/tui-enable-transparency)
#+end_src

*** Spacious Padding
This package provides a global minor mode to increase the spacing/padding of Emacs windows and frames.
#+begin_src emacs-lisp
  ;; (use-package spacious-padding
  ;;   :custom
  ;;   (line-spacing 3)
  ;;   (spacious-padding-mode 1))
#+end_src

*** Centered text column (Olivetti)
Text centered reading and writing experience.
#+begin_src emacs-lisp
  (use-package olivetti
    :custom
    (olivetti-body-width 80)
    :hook
    (text-mode . olivetti-mode)
    (org-mode . olivetti-mode))
#+end_src

** Doom Modeline
A fancy, fast and customizable mode-line.
#+begin_src emacs-lisp
    (use-package doom-modeline
      :custom
      (doom-modeline-height 25) ;; Set modeline height
      :hook (after-init . doom-modeline-mode))
#+end_src

** Nerd Icons
This is an icon set that can be used with dired, ibuffer and other Emacs packages.
Don't forget nerd-icons-install-fonts to install the resource fonts.

We use nerd-icons because it supports both GUI and TUI unlike all-the-icons.
Also Doom modeline requires nerd icons.
#+begin_src emacs-lisp
    (use-package nerd-icons :defer)

    (use-package nerd-icons-dired
      :hook (dired-mode . nerd-icons-dired-mode))

    (use-package nerd-icons-ibuffer
      :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src
* Core packages
** Navigation (avy + ace-link + ace-window)
*** Avy
Line and to-word jumping with markers.
#+begin_src emacs-lisp
    (use-package avy
      :bind (
             ("M-j" . avy-goto-char-timer)
             ("M-k" . avy-goto-line)))
#+end_src
*** ace-link
Avy-based link jumping.
#+begin_src emacs-lisp
  (use-package ace-link
    :config
    (ace-link-setup-default)
    (global-set-key (kbd "M-O") 'ace-link-addr))
    (with-eval-after-load 'org
      (define-key org-mode-map (kbd "M-O") 'ace-link-org))
#+end_src
*** reboud other-window
#+begin_src emacs-lisp
  (global-set-key (kbd "M-o") 'other-window)
#+end_src

*** [unused] ace-window
#+begin_src emacs-lisp :tangle no
  (use-package ace-window
    :bind ("M-O" . ace-window)
    :custom
    (aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
#+end_src
** Better Help (Helpful + Which-key)
*** Helpful
An alternative to the built-in Emacs help that provides much more
contextual information.
#+begin_src emacs-lisp
    (use-package helpful
      :bind
      ;; Note that the built-in `describe-function' includes both functions
      ;; and macros. `helpful-function' is functions only, so we provide
      ;; `helpful-callable' as a drop-in replacement.
      ("C-h f" . helpful-callable)
      ("C-h v" . helpful-variable)
      ("C-h k" . helpful-key)
      ("C-h x" . helpful-command)
      )
#+end_src

*** Which-Key
Which-key is a helper utility for keychords (which key to press).
#+begin_src emacs-lisp
    (use-package which-key
      :ensure nil ;; Don't install which-key because it's now built-in
      :hook (after-init . which-key-mode)
      :diminish
      :custom
      (which-key-side-window-location 'bottom)
      (which-key-sort-order #'which-key-key-order-alpha) ;; Same as default, except single characters are sorted alphabetically
      (which-key-sort-uppercase-first nil)
      (which-key-add-column-padding 1) ;; Number of spaces to add to the left of each column
      (which-key-min-display-lines 6)  ;; Increase the minimum lines to display because the default is only 1
      (which-key-idle-delay 0.8)       ;; Set the time delay (in seconds) for the which-key popup to appear
      (which-key-max-description-length 25)
      (which-key-allow-imprecise-window-fit nil)) ;; Fixes which-key window slipping out in Emacs Daemon
#+end_src

** Minibuffer (Vertico + Marginalia)
- Vertico: Provides a performant and minimalistic vertical completion
  UI based on the default completion system.
- Savehist: Saves completion history.
- Marginalia: Adds extra metadata for completions in the margins (like
  descriptions).
- Nerd-icons-completion: Adds icons to completion candidates using the
  built in completion metadata functions.

We use these packages because they use Emacs native functions. Unlike
Ivy or Helm.  One alternative is ivy and counsel, check out the
[[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] for more information.

#+begin_src emacs-lisp
  (use-package vertico
    :hook (after-init . vertico-mode)
    ;; Vim keybinds
    ;; :bind (:map vertico-map
    ;;            ("C-j" . vertico-next)
    ;;            ("C-k" . vertico-previous)
    ;;            ("C-u" . vertico-scroll-down)
    ;;            ("C-d" . vertico-scroll-up))
    :custom
    (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    )

  (savehist-mode) ;; Enables save history mode

  (use-package marginalia
    :after vertico
    :config
    (marginalia-mode))

  (use-package nerd-icons-completion
    :after marginalia
    :config
    (nerd-icons-completion-mode)
    :hook
    (marginalia-mode . nerd-icons-completion-marginalia-setup))
#+end_src

** Completion (Corfu + Cape + Orderless)
*** Corfu
Enhances in-buffer completion with a small completion popup.
Corfu is a small package, which relies on the Emacs completion facilities and concentrates on providing a polished completion.
For more configuration options check out their [[https://github.com/minad/corfu][git repository]].
Notes:
- To enter Orderless field separator, use M-SPC.
#+begin_src emacs-lisp
  (use-package corfu
    ;; Optional customizations
    :custom
    (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-auto nil)                 ;; Enable auto completion
    (corfu-auto-prefix 2)          ;; Minimum length of prefix for auto completion.
    (corfu-popupinfo-mode t)       ;; Enable popup information
    (corfu-popupinfo-delay 0.5)    ;; Lower popup info delay to 0.5 seconds from 2 seconds
    (corfu-separator ?\s)          ;; Orderless field separator, Use M-SPC to enter separator
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
    ;; (corfu-scroll-margin 5)        ;; Use scroll margin
    (completion-ignore-case t)

    ;; Emacs 30 and newer: Disable Ispell completion function.
    ;; Try `cape-dict' as an alternative.
    (text-mode-ispell-word-completion nil)

    ;; Enable indentation+completion using the TAB key.
    ;; `completion-at-point' is often bound to M-TAB.
    (tab-always-indent 'complete)

    (corfu-preview-current nil) ;; Don't insert completion without confirmation
    ;; Recommended: Enable Corfu globally.  This is recommended since Dabbrev can
    ;; be used globally (M-/).  See also the customization variable
    ;; `global-corfu-modes' to exclude certain modes.
    :init
    (global-corfu-mode)
    :bind (
        :map corfu-map
            ("RET" . nil)
            ("<return>" . nil)
            ([remap keyboard-escape-quit] . nil)
            ("ESC" . corfu-quit)
            ("<escape>" . corfu-quit)))

  (use-package nerd-icons-corfu
    :after corfu
    :init (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

*** Cape
Provides Completion At Point Extensions which can be used in combination with Corfu, Company or the default completion UI.

We merge capfs together so they appear together in the completion list.
The ones not merged will display separately (Only their list will show up in the completion list).
Order matters. Since these functions run in sequence, the first one to return a list will prevent others from running.
Due to technical details, not all Capfs can be merged successfully (e.g cape-file).

Notes:
- Be aware when adding Capfs (Completion-at-point-functions) to the list since each of the Capfs adds a small runtime cost.
Read the [[https://github.com/minad/cape#configuration][configuration section]] in Cape's readme for more information.
#+begin_src emacs-lisp
  (use-package yasnippet-capf :defer)

  (defun start/setup-capfs ()
    "Configure completion backends"
    ;; Take care when adding Capfs to the list since each of the Capfs adds a small runtime cost.
    (let ((merge-backends (list
                           #'cape-keyword      ;; Keyword completion
                           ;; #'cape-abbrev       ;; Complete abbreviation
                           #'cape-dabbrev      ;; Complete word from current buffers
                           ;; #'cape-line         ;; Complete entire line from current buffer
                           ;; #'cape-history      ;; Complete from Eshell, Comint or minibuffer history
                           ;; #'cape-dict         ;; Dictionary completion (Needs Dictionary file installed)
                           ;; #'cape-tex          ;; Complete Unicode char from TeX command, e.g. \hbar
                           ;; #'cape-sgml         ;; Complete Unicode char from SGML entity, e.g., &alpha
                           ;; #'cape-rfc1345      ;; Complete Unicode char using RFC 1345 mnemonics
                           ;; #'snippy-capf       ;; Vscode Snippets (Snippy needs to be installed)
                           #'yasnippet-capf    ;; Yasnippet snippets
                           ))
          (seperate-backends (list
                              #'cape-file ;; Path completion
                              #'cape-elisp-block ;; Complete elisp in Org or Markdown mode
                              )))
      ;; Remove keyword completion in git commits
      (when (derived-mode-p 'git-commit-mode)
        (setq merge-backends (remq #'cape-keyword merge-backends)))

      ;; Add Elisp symbols only in Elisp modes
      (when (derived-mode-p 'emacs-lisp-mode 'ielm-mode)
        (setq merge-backends (cons #'cape-elisp-symbol merge-backends))) ;; Emacs Lisp code (functions, variables)

      ;; Add Eglot to the front of the list if it's active
      (when (bound-and-true-p eglot--managed-mode)
        (setq merge-backends (cons #'eglot-completion-at-point
   merge-backends)))

      ;; Create the super-capf and set it buffer-locally
      (setq-local completion-at-point-functions
                  (append
                   seperate-backends
                   (list (apply #'cape-capf-super merge-backends)))
                  )))

  (use-package cape
    :after (corfu)
    :init
    ;; Add to the global default value of `completion-at-point-functions' which is
    ;; used by `completion-at-point'.  The order of the functions matters, the
    ;; first function returning a result wins.  Note that the list of buffer-local
    ;; completion functions takes precedence over the global list.

    ;; Seperate function needed, because we use setq-local (everything is replaced)
    (add-hook 'eglot-managed-mode-hook #'start/setup-capfs)
    (add-hook 'prog-mode-hook #'start/setup-capfs)
    (add-hook 'text-mode-hook #'start/setup-capfs))
#+end_src

*** Orderless
Completion style that divides the pattern into space-separated
components and matches candidates that match all of the components in
any order.  Recommended for packages like vertico, corfu.
#+begin_src emacs-lisp
    (use-package orderless
      :defer
      :custom
      (completion-styles '(orderless basic))
      (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src
** Eat (Emulate A Terminal)
Eat is a terminal emulator within Emacs.
It's more portable and less overhead for users over like vterm or eshell.
We setup eat with eshell, if you want to use bash, zsh etc., check out their git [[https://codeberg.org/akib/emacs-eat][repository]] how to do it.

If you want a faster and more responsive terminal emulator try out vterm.
#+begin_src emacs-lisp
    (use-package eat
      :defer
      :hook ('eshell-load-hook #'eat-eshell-mode))
#+end_src

*** Exec-path-from-shell
Make Emacs use the $PATH set up by the user's shell
#+begin_src emacs-lisp
    (use-package exec-path-from-shell
      :hook (after-init . exec-path-from-shell-initialize))
#+end_src
** Version Control (Magit + Diff-hl)
*** Magit
Complete text-based user interface to Git.
#+begin_src emacs-lisp
  (use-package transient
    :defer
    :config
    (define-key transient-map (kbd "<escape>") 'transient-quit-one)) ;; Make escape quit magit prompts

  (use-package magit
    :defer
    :custom (magit-diff-refine-hunk (quote all)) ;; Shows inline diff
    :config
    (setopt magit-format-file-function #'magit-format-file-nerd-icons) ;; Magit nerd icons
    )
*** Diff-hl
Highlights uncommitted changes on the left side of the window (area also known as the "gutter"), allows you to jump between and revert them selectively.
#+begin_src emacs-lisp
    (use-package diff-hl
      :hook ((dired-mode         . diff-hl-dired-mode-unless-remote)
             (magit-post-refresh . diff-hl-magit-post-refresh)
             (after-init . global-diff-hl-mode)))
#+end_src
*** Ediff
#+begin_src emacs-lisp
  (use-package ediff
    :ensure nil
    :custom
    (ediff-keep-variants nil)
    (ediff-split-window-function 'split-window-horizontally)
    (ediff-window-setup-function 'ediff-setup-windows-plain))
#+end_src
** Miscellaneous (undos todos & generally prettify)
*** Recent files
Track recently opened, written and killed buffers.
#+begin_src emacs-lisp
  (use-package recentf
    :config
    (recentf-mode t)
    :custom
    (recentf-max-saved-items 50)
    :bind
    (("C-c w r" . recentf-open)))
#+end_src
*** Undo
Undotree like setup.

Undo Fu: Simple, stable linear undo with redo for Emacs.
Undo-fu-session: Persistent undo history
Vundo: Visualizes undo history.


If you want to use this. Don't forget to add keybindings for undu-fu and vundo.
Evil users don't need to add keybindings for undo-fu just change evil-undo-system to undo-fu.

#+begin_src emacs-lisp
  (use-package undo-fu
    :defer
    :config
    ;; Increase undo history limits to reduce likelihood of data loss
    (setq undo-limit (* 1024 1024 64)          ;; 64mb  (default is 160kb)
          undo-strong-limit (* 1024 1024 96)   ;; 96mb  (default is 240kb)
          undo-outer-limit (* 1024 1024 960))) ;; 960mb (default is 24mb)

  (use-package undo-fu-session
    :hook (after-init . undo-fu-session-global-mode)
    :custom (undo-fu-session-incompatible-files '("\\.gpg$" "/COMMIT_EDITMSG\\'" "/git-rebase-todo\\'"))
    :config
    (when (executable-find "zstd")
      ;; There are other algorithms available, but zstd is the fastest, and speed
      ;; is our priority within Emacs
      (setq undo-fu-session-compression 'zst)))

  (use-package vundo
    :defer
    :custom
    (vundo-glyph-alist vundo-unicode-symbols)
    (vundo-compact-display t)
    (add-hook 'vundo-mode-hook (lambda () (visual-line-mode -1))))
#+end_src
*** Hl-todo
Highlight TODO keywords.
#+begin_src emacs-lisp
  (use-package hl-todo
    :hook
    ((prog-mode yaml-ts-mode) . hl-todo-mode)
    :config
    ;; From doom emacs
    (setq hl-todo-highlight-punctuation ":"
          hl-todo-keyword-faces
          '(;; For reminders to change or add something at a later date.
            ("TODO" warning bold)
            ;; For code (or code paths) that are broken, unimplemented, or slow,
            ;; and may become bigger problems later.
            ("FIXME" error bold)
            ;; For code that needs to be revisited later, either to upstream it,
            ;; improve it, or address non-critical issues.
            ("REVIEW" font-lock-keyword-face bold)
            ;; For code smells where questionable practices are used
            ;; intentionally, and/or is likely to break in a future update.
            ("HACK" font-lock-constant-face bold)
            ;; For sections of code that just gotta go, and will be gone soon.
            ;; Specifically, this means the code is deprecated, not necessarily
            ;; the feature it enables.
            ("DEPRECATED" font-lock-doc-face bold)
            ;; Extra keywords commonly found in the wild, whose meaning may vary
            ;; from project to project.
            ("NOTE" success bold)
            ("BUG" error bold)
            ("XXX" font-lock-constant-face bold)))
    )
#+end_src

*** Rainbow Delimiters
Adds colors to brackets.
#+begin_src emacs-lisp
    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

*** Ws-butler
Removes whitespace from the ends of lines.
#+begin_src emacs-lisp
    (use-package ws-butler
      :hook (after-init . ws-butler-global-mode))
#+end_src

*** Bookmarks
Bookmark delete bind.
#+begin_src emacs-lisp
  (use-package bookmark
    :custom
    (bookmark-save-flag 1)
    :bind
    ("C-x r d" . bookmark-delete))
#+end_src

** Consult
Provides search and navigation commands based on the Emacs completion function.
Telescope for Emacs.
Check out their [[https://github.com/minad/consult][git repository]] for more awesome functions.
#+begin_src emacs-lisp
  (use-package consult
    ;; Enable automatic preview at point in the *Completions* buffer. This is
    ;; relevant when you use the default completion UI.
    :hook (completion-list-mode . consult-preview-at-point-mode)
    :init
    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0.5
          register-preview-function #'consult-register-format)

    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    :config
    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key "M-.")
    ;; (setq consult-preview-key '("S-<down>" "S-<up>"))

    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    ;; (consult-customize
    ;; consult-theme :preview-key '(:debounce 0.2 any)
    ;; consult-ripgrep consult-git-grep consult-grep
    ;; consult-bookmark consult-recent-file consult-xref
    ;; consult--source-bookmark consult--source-file-register
    ;; consult--source-recent-file consult--source-project-recent-file
    ;; :preview-key "M-."
    ;; :preview-key '(:debounce 0.4 any))

    ;; By default `consult-project-function' uses `project-root' from project.el.
    ;; Optionally configure a different project root function.
     ;;;; 1. project.el (the default)
    ;; (setq consult-project-function #'consult--default-project--function)
     ;;;; 2. vc.el (vc-root-dir)
    ;; (setq consult-project-function (lambda (_) (vc-root-dir)))
     ;;;; 3. locate-dominating-file
    ;; (setq consult-project-function (lambda (_) (locate-dominating-file "." ".git")))
     ;;;; 4. projectile.el (projectile-project-root)
    (autoload 'projectile-project-root "projectile")
    (setq consult-project-function (lambda (_) (projectile-project-root)))
     ;;;; 5. No project support
    ;; (setq consult-project-function nil)
    )
#+end_src

* File management & opening
** Dired
Directory Editor of Emacs.
#+begin_src emacs-lisp
  (use-package dired
    :ensure
    nil
    :commands
    (dired dired-jump)
    :custom
    (dired-listing-switches
     "-goah --group-directories-first --time-style=long-iso")
    (dired-listing-switches "-lth")
    (dired-dwim-target t)
    (delete-by-moving-to-trash t)
    :init
    (put 'dired-find-alternate-file 'disabled nil))

  ;; Hide or display hidden files

  (use-package dired
    :ensure nil
    :hook
    (dired-mode . dired-omit-mode)
    (dired-mode . dired-hide-details-mode)
    :bind (:map dired-mode-map
                ( "."     . dired-omit-mode))
    :custom (dired-omit-files "^\\.[a-zA-Z0-9]+"))

  ;; Backup files

  (setq-default backup-directory-alist
                `(("." . ,(expand-file-name "backups/" user-emacs-directory)))
                version-control t
                delete-old-versions t
                create-lockfiles nil)
#+end_src
** Viewing files (& externally)
Packages for comsumption without leaving emacs.
*** pdf-tools
Advanced reader and more.
#+begin_src emacs-lisp
  (use-package pdf-tools
    :mode ("\\.pdf\\'" . pdf-view-mode)
    :config
    (pdf-tools-install)
    (require 'pdf-roll nil t)
    :custom
    (pdf-view-display-size 'fit-page)
    (pdf-view-use-scaling t)
    (pdf-view-midnight-colors '("#ffffff" . "#1e1e1e")))
#+end_src
*** nov.el (epub)
Read ePub files
#+begin_src emacs-lisp
  (use-package nov
    :init
    (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode)))
#+end_src
*** elfeed (rss feed reader)
Read RSS feeds with Elfeed
#+begin_src emacs-lisp
  (use-package elfeed
    :custom
    (elfeed-db-directory
     (expand-file-name "elfeed" user-emacs-directory))
    (elfeed-show-entry-switch 'display-buffer)
    :bind
    ("C-c w e" . elfeed))

  ;; Configure Elfeed with org mode

  (use-package elfeed-org
    :config
    (elfeed-org)
    :custom
    (rmh-elfeed-org-files
     (list (concat (file-name-as-directory (getenv "HOME"))
  		 "elfeed.org"))))
#+end_src
*** images (gimp)
Image viewer
#+begin_src emacs-lisp
  (use-package emacs
    :custom
    (image-dired-external-viewer "gimp")
    :bind
    ((:map image-mode-map
           ("k" . image-kill-buffer)
           ("<right>" . image-next-file)
           ("<left>"  . image-previous-file))
     (:map dired-mode-map
           ("C-<return>" . image-dired-dired-display-external))))

  (use-package image-dired
    :bind
    (("C-c w I" . image-dired))
    (:map image-dired-thumbnail-mode-map
          ("C-<right>" . image-dired-display-next)
          ("C-<left>"  . image-dired-display-previous)))
#+end_src
*** emms (Music)
Emacs Multimedia System
#+begin_src emacs-lisp
  (use-package emms
    :config
    (require 'emms-setup)
    (require 'emms-mpris)
    (emms-all)
    (emms-default-players)
    (emms-mpris-enable)
    :custom
    (emms-browser-covers #'emms-browser-cache-thumbnail-async)
    :bind
    (("C-c w m b" . emms-browser)
     ("C-c w m e" . emms)
     ("C-c w m p" . emms-play-playlist )
     ("<XF86AudioPrev>" . emms-previous)
     ("<XF86AudioNext>" . emms-next)
     ("<XF86AudioPlay>" . emms-pause)))
#+end_src

*** dired-x (Open externally)
Generic file opening with system applications directly from Dired. Use
'&' (dired-do-async-shell-command) on a file to trigger these rules.
#+begin_src emacs-lisp
  (use-package dired-x
    :ensure nil
    :custom
    (dired-guess-shell-alist-user
     '(("\\.\\(png\\|jpe?g\\|tiff\\|gif\\|webp\\)\\'" "feh")
       ("\\.\\(mp[34]\\|m4a\\|ogg\\|flac\\|webm\\|mkv\\)\\'" "mpv")
       (".*" "xdg-open"))))
#+end_src

* Writing
Emacs contains many “editing modes” that alter its basic behavior in
useful ways. These are divided into “major modes” and “minor modes”.
For more: C-h i: g: (emacs)Modes

Some programming languages require the installation of specific modes
to fully integrate and function within Emacs. These packages are often
necessary for features like syntax highlighting, code formatting,
linting, and language-specific features.

Example, how to setup a language mode. Use C-SPC tab to uncomment the
lines. *To use it, remove :tangle no from the beginning of the source
code block.*
#+begin_src emacs-lisp :tangle no
  (use-package lua-mode
    :mode "\\.lua\\'") ;; Only start in a lua file
#+end_src

** Org Mode
One of the things that Emacs is loved for.  Once you've used it for a
bit, you'll understand why people love it. Even reading about it can
be inspiring!  For example, this document is effectively the source
code and descriptions bound into the one document, much like the
literate programming ideas that Donald Knuth made famous.

We use an Org mode document for our Emacs configuration because it
provides:
- Better organization:  It lets us structure  with outlines, headings,
  and tags.
- Literate Documentation: It's a document, not just source code.
- Fast Navigation: Quickly jump to sections with something like Imenu.

If you consider using org mode even more. Check out the [[https://github.com/minad/org-modern][org-modern]] package.
It makes org mode really beautiful.
Don't forget to remove org-superstar if you want to use it.

For templates use C-c C-,
Much easier than org-tempo
#+begin_src emacs-lisp
  (use-package org
    :ensure nil
    :custom
    ;; (org-edit-src-content-indentation 4) ;; Set src block automatic indent to 4 instead of 2.
    (org-return-follows-link t)   ;; Sets RETURN key in org-mode to follow links
    (org-hide-emphasis-markers t)
    (org-startup-with-inline-images t)
    (org-image-actual-width '(450))
    (org-pretty-entities t)
    ;; (org-use-sub-superscripts "{}")
    (org-id-link-to-org-use-id t)
    (org-fold-catch-invisible-edits 'show)
    (org-agenda-custom-commands
     '(("e" "Agenda, next actions and waiting"
        ((agenda "" ((org-agenda-overriding-header "Next three days:")
                     (org-agenda-span 3)
                     (org-agenda-start-on-weekday nil)))
         (todo "NEXT" ((org-agenda-overriding-header "Next Actions:")))
         (todo "WAIT" ((org-agenda-overriding-header "Waiting:")))))))
  :bind
  (("C-c a" . org-agenda)))
#+end_src

**** Table of Contents
#+begin_src emacs-lisp
    (use-package toc-org
      :commands toc-org-enable
      :hook (org-mode . toc-org-mode))
#+end_src

**** Org Superstar
Prettify headings and plain lists in Org mode. Modern version of org-bullets.
#+begin_src emacs-lisp
    (use-package org-superstar
      :after org
      :hook (org-mode . org-superstar-mode))
#+end_src

**** Org Appear
Invisible elements visible under cursor position.
#+begin_src emacs-lisp
  (use-package org-appear
    :hook
    (org-mode . org-appear-mode))
#+end_src

**** Org insert hyperlink
#+begin_src emacs-lisp
  (use-package org-web-tools
    :bind
    (("C-c w w" . org-web-tools-insert-link-for-url)))
#+end_src

** text mode
#+begin_src emacs-lisp
  (use-package text-mode
    :ensure
    nil
    :hook
    (text-mode . visual-line-mode)
    :custom
    (sentence-end-double-space nil)
    (scroll-error-top-bottom t)
    (save-interprogram-paste-before-kill t))
#+end_src

** Emacs writing studio variables autoload & executables check
Custom variables autoload.
#+begin_src emacs-lisp
  (load-file (concat (file-name-as-directory user-emacs-directory)
                     "ews.el"))
  (ews-missing-executables
   '(("gs" "mutool")
     "pdftotext"
     "soffice"
     "zip"
     "ddjvu"
     "curl"
     ("mpg321" "ogg123" "mplayer" "mpv" "vlc")
     ("grep" "ripgrep")
     ("convert" "gm")
     "dvipng"
     "latex"
     "hunspell"
     "git"))
#+end_src

** Notetaking (org + denote + consult)
Fleeting notes configuration.
#+begin_src emacs-lisp
    (use-package org
      :bind
      (("C-c c" . org-capture)
       ("C-c l" . org-store-link))
      :custom
      (org-capture-templates
       '(("f" "Fleeting note"
          item
          (file+headline org-default-notes-file "Notes")
          "- %?")
         ("p" "Permanent note" plain
          (file denote-last-path)
          #'denote-org-capture
          :no-save t
          :immediate-finish nil
          :kill-buffer t
          :jump-to-captured t)
         ("t" "New task" entry
          (file+headline org-default-notes-file "Tasks")
          "* TODO %i%?"))))

    ;; Denote

    (use-package denote
      :defer t
      :custom
      (denote-sort-keywords t)
      (denote-link-description-function #'ews-denote-link-description-title-case)
      (denote-rename-buffer-mode 1)
      :hook
      (dired-mode . denote-dired-mode)
      :custom-face
      (denote-faces-link ((t (:slant italic))))
      :bind
      (("C-c w d b" . denote-find-backlink)
       ("C-c w d d" . denote-date)
       ("C-c w d l" . denote-find-link)
       ("C-c w d i" . denote-link-or-create)
       ("C-c w d k" . denote-rename-file-keywords)
       ("C-c w d n" . denote)
       ("C-c w d r" . denote-rename-file)
       ("C-c w d R" . denote-rename-file-using-front-matter)))

    ;; Denote auxiliary packages

    (use-package denote-journal)

    (use-package denote-org
      :bind
      (("C-c w d h" . denote-org-link-to-heading)))

    (use-package denote-sequence)

    ;; Consult convenience functions
    (use-package consult
      :bind
      (("C-c w h" . consult-org-heading)
       ("C-c w g" . consult-ripgrep)
       ("C-c w G" . baej-consult-ripgrep-docs) ;; described in custom functions
       ("C-c w F" . baej-consult-fd-docs) ;; described in custom functions
       ("C-c w f" . consult-fd))
      :config
      (add-to-list 'consult-preview-allowed-hooks 'visual-line-mode))

    ;; Consult-Notes for easy access to notes

    (use-package consult-notes
      :custom
      (consult-notes-denote-display-keywords-indicator "_")
      :bind
      (("C-c w d f" . consult-notes)
       ("C-c w d g" . consult-notes-search-in-all-notes))
      :init
      (consult-notes-denote-mode))

    ;; Citar-Denote to manage literature notes

    (use-package citar-denote
      :custom
      (citar-open-always-create-notes t)
      (citar-denote-subdir "literature")
      :init
      (citar-denote-mode)
      :bind
      (("C-c w b c" . citar-create-note)    ;; Create a bibliographic note
       ("C-c w b n" . citar-denote-open-note)
       ("C-c w b x" . citar-denote-nocite)
       :map org-mode-map
       ("C-c w b k" . citar-denote-add-citekey)
       ("C-c w b K" . citar-denote-remove-citekey)
       ("C-c w b d" . citar-denote-dwim)
       ("C-c w b e" . citar-denote-open-reference-entry)))

    ;; Explore and manage your Denote collection

    (use-package denote-explore
      :bind
      (;; Statistics
       ("C-c w x c" . denote-explore-count-notes)
       ("C-c w x C" . denote-explore-count-keywords)
       ("C-c w x b" . denote-explore-barchart-keywords)
       ("C-c w x e" . denote-explore-barchart-filetypes)
       ;; Random walks
       ("C-c w x r" . denote-explore-random-note)
       ("C-c w x l" . denote-explore-random-link)
       ("C-c w x k" . denote-explore-random-keyword)
       ("C-c w x x" . denote-explore-random-regex)
       ;; Denote Janitor
       ("C-c w x d" . denote-explore-identify-duplicate-notes)
       ("C-c w x z" . denote-explore-zero-keywords)
       ("C-c w x s" . denote-explore-single-keywords)
       ("C-c w x o" . denote-explore-sort-keywords)
       ("C-c w x w" . denote-explore-rename-keyword)
       ;; Visualise denote
       ("C-c w x n" . denote-explore-network)
       ("C-c w x v" . denote-explore-network-regenerate)
       ("C-c w x D" . denote-explore-barchart-degree)))

    ;; Set some Org mode shortcuts

    (use-package org
      :bind
      (:map org-mode-map
            ("C-c w n" . ews-org-insert-notes-drawer)
            ("C-c w p" . ews-org-insert-screenshot)
            ("C-c w c" . ews-org-count-words)))
#+end_src

*** Lorem ipsum insert
#+begin_src emacs-lisp
(use-package lorem-ipsum
    :custom
    (lorem-ipsum-list-bullet "- ") ;; Org mode bullets
    :init
    (setq lorem-ipsum-sentence-separator
          (if sentence-end-double-space "  " " "))
    :bind
    (("C-c w i" . lorem-ipsum-insert-paragraphs)))
#+end_src

** Bibliography
Biblio package for looking up doi and arXiv paper metadata.
#+begin_src emacs-lisp
  (use-package biblio
    :bind
    (("C-c w b b" . ews-bibtex-biblio-lookup)))
#+end_src

*** Bibtex
Bibtex for editing the `.bib` file.
#+begin_src emacs-lisp
    (use-package bibtex
      :custom
      (bibtex-autokey-names 1)
      (bibtex-autokey-year-length 2)
      (bibtex-autokey-titlewords 0)

      (bibtex-autokey-name-year-separator "")
      (bibtex-autokey-year-title-separator "")
      (bibtex-autokey-titleword-separator "")

      (bibtex-autokey-name-change-strings
       '(("ą" . "a") ("ć" . "c") ("ę" . "e") ("ł" . "l") ("ń" . "n")
         ("ó" . "o") ("ś" . "s") ("ż" . "z") ("ź" . "z")
         ("Ą" . "A") ("Ć" . "C") ("Ę" . "E") ("Ł" . "L") ("Ń" . "N")
         ("Ó" . "O") ("Ś" . "S") ("Ż" . "Z") ("Ź" . "Z")))
      (bibtex-user-optional-fields
       '(("keywords" "Keywords to describe the entry" "")
         ("file"     "Relative or absolute path to attachments" "" )))
      (bibtex-align-at-equal-sign t)
      :config
      (ews-bibtex-register)
      :bind
      (("C-c w b r" . ews-bibtex-register))
      :hook
      (bibtex-mode . (lambda () (setq-local completion-at-point-functions nil))))
#+end_src

*** Citar package
#+begin_src emacs-lisp
  ;; Citar to access bibliographies

  (use-package citar
    :defer t
    :custom
    (citar-bibliography ews-bibtex-files)
    :bind
    (("C-c w b o" . citar-open)))
#+end_src

** Spell check (Sideline-flymake)
Show flymake errors with sideline.
#+begin_src emacs-lisp
    (use-package sideline-flymake
      :hook (flymake-mode . sideline-mode)
      :custom
      (sideline-flymake-display-mode 'line) ;; Show errors on the current line
      (sideline-backends-right '(sideline-flymake)))
#+end_src
** Export
Exporting citations with Org Mode.
#+begin_src emacs-lisp
  (require 'oc-natbib)
  (require 'oc-csl)

  (setq org-cite-global-bibliography ews-bibtex-files
        org-cite-insert-processor 'citar
        org-cite-follow-processor 'citar
        org-cite-activate-processor 'citar)

  (use-package org
    :custom
    (org-export-with-drawers nil)
    (org-export-with-todo-keywords nil)
    (org-export-with-toc nil)
    (org-export-with-smart-quotes t)
    (org-export-date-timestamp-format "%e %B %Y"))

  (use-package ox-epub
    :demand t
    :init
    (require 'ox-org))
  (use-package ox-latex
    :ensure nil
    :demand t
    :custom
    ;; Multiple LaTeX passes for bibliographies
    (org-latex-pdf-process
     '("pdflatex -interaction nonstopmode -output-directory %o %f"
       "bibtex %b"
       "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
       "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
    ;; Clean temporary files after export
    (org-latex-logfiles-extensions
     (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out"
             "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk"
             "blg" "brf" "fls" "entoc" "ps" "spl" "bbl"
             "tex" "bcf"))))

  (with-eval-after-load 'ox-latex
    (add-to-list
     'org-latex-classes
     '("ews"
       "\\documentclass[11pt, twoside, hidelinks]{memoir}
          \\setstocksize{9.25in}{7.5in}
          \\settrimmedsize{\\stockheight}{\\stockwidth}{*}
          \\setlrmarginsandblock{1.5in}{1in}{*}
          \\setulmarginsandblock{1in}{1.5in}{*}
          \\checkandfixthelayout
          \\layout
          \\setcounter{tocdepth}{0}
          \\renewcommand{\\baselinestretch}{1.25}
          \\setheadfoot{0.5in}{0.75in}
          \\setlength{\\footskip}{0.8in}
          \\chapterstyle{bianchi}
          \\setsecheadstyle{\\normalfont \\raggedright \\textbf}
          \\setsubsecheadstyle{\\normalfont \\raggedright \\emph}
          \\setsubsubsecheadstyle{\\normalfont\\centering}
          \\pagestyle{myheadings}
          \\usepackage[font={small, it}]{caption}
          \\usepackage{ccicons}
          \\usepackage{ebgaramond}
          \\usepackage[authoryear]{natbib}
          \\bibliographystyle{apalike}
          \\usepackage{svg}
  \\hyphenation{mini-buffer}"
       ("\\chapter{%s}" . "\\chapter*{%s}")
       ("\\section{%s}" . "\\section*{%s}")
       ("\\subsection{%s}" . "\\subsection*{%s}")
       ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))))
#+end_src

* Trying out - packages
All the package setups that don't need much tweaking.
** Embark
Emacs Mini-Buffer Actions Rooted in Keymaps. Right click like menu for Emacs.
#+begin_src emacs-lisp :tangle no
    (use-package embark :defer)
    (use-package embark-consult
      :hook
      (embark-collect-mode . consult-preview-at-point-mode))
#+end_src
* Coding
** Projectile
Project interaction library for Emacs.

Emacs has a built in project manager called project.el, but we don't use it.
You can try it out with the keybinds under C-x p because project.el does not require any special setup to use.

We use projectile because it:
- supports more features and project types.
- has better integration with projects.
- has better documentation.
- is developed faster.
More [[https://docs.projectile.mx/projectile/projectile_vs_project.html][reasons]] to use projectile.

You can also make the [[https://github.com/karthink/consult-dir][consult-dir]] package list all the directories you [[https://github.com/MiniApollo/config/blob/main/emacs/init.org#consult-dir][specified]] and search from them like in tmux-sessionizer.
#+begin_src emacs-lisp
    (use-package projectile
      :hook (after-init . projectile-mode)
      :config
      (projectile-mode)
      :custom
      ;; (projectile-auto-discover nil) ;; Disable auto search for better startup times ;; Search with a keybind
      (projectile-run-use-comint-mode t) ;; Interactive run dialog when running projects inside emacs (like giving input)
      (projectile-switch-project-action #'projectile-dired) ;; Open dired when switching to a project
      (projectile-project-search-path '("~/org/org-roam" "~/Projekty/" ("~/github" . 1)))) ;; . 1 means only search the first subdirectory level for projects
#+end_src
** LSP (Eglot + Mason)
*** Eglot
Built in Emacs client for the Language Server Protocol.  We use Eglot
because it is fast and minimal.  For more: C-h i: g: (eglot)Top

Eglot does not automatically download LSP servers. It requires
separate download.  The easiest way to install LSP servers is with a
package manager like mason.el.

If you can't use a package manager you can do the following:
- Download the server (e.g. from github)
- Add the binary/executable to your path.
- Or customize the eglot-server-programs list.
To control how a LSP server is started customize the
eglot-server-programs list.

There are many alternative LSP clients, one of them is LSP-mode.
Which has more features and supports automatic language server
installation.  But it's bigger, so it has more moving parts.

We don't use it because Eglot is more than enough for most people.
If you want to use LSP mode check out their [[https://emacs-lsp.github.io/lsp-mode/][documentation]] or the [[https://github.com/MiniApollo/kickstart.emacs/wiki][project wiki]] page for more information.
#+begin_src emacs-lisp :tangle no
    (use-package eglot
      :ensure nil ;; Don't install eglot because it's now built-in
      :hook ((c-mode c++-mode ;; Autostart lsp servers for a given mode
                     lua-mode) ;; Lua-mode needs to be installed
             . eglot-ensure)
      :custom
      ;; Good default
      (eglot-events-buffer-size 0) ;; No event buffers (LSP server logs)
      (eglot-autoshutdown t);; Shutdown unused servers.
      (eglot-report-progress nil) ;; Disable LSP server logs (Don't show lsp messages at the bottom, java)
      ;; Manual lsp servers
      ;;:config
      ;;(add-to-list 'eglot-server-programs
      ;;             `(lua-mode . ("PATH_TO_THE_LSP_FOLDER/bin/lua-language-server" "-lsp"))) ;; Adds our lua lsp server to eglot's server list
      )
#+end_src

*** Mason.el
Package manager for LSP, DAP, linters, and more for the Emacs Operating System.
I waited so long for a package like this.
If you plan to use something like LSP-mode don't forget to remove this.
#+begin_src emacs-lisp
    (use-package mason
      :hook (after-init . mason-ensure))
#+end_src

** Tree-Sitter
A parser generator tool and an incremental parsing library.
Check out TJ's [[https://www.youtube.com/watch?v=09-9LltqWLY][video]] to learn why you should use it.

With Emacs 29 Tree-Sitter is now built-in. You may need to compile Emacs from source to have it enabled.
You also need to have a compiler installed so Emacs can compile the parsers into a shared library.
For more info about how to use Tree-Sitter check out this [[https://www.masteringemacs.org/article/how-to-get-started-tree-sitter][masteringemacs]] article.

Using Tree-Sitter is somewhat hacky because it requires you to:
- manually manage a source list of the parsers you want to use.
- remap the major modes you want to use.
You can also use treesit-auto, but it is updated quite slowly so we don't use it.

To explore the current buffer's syntax tree, use the treesit-explore-mode command.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
    (setq treesit-language-source-alist
          '((bash "https://github.com/tree-sitter/tree-sitter-bash")
            (cmake "https://github.com/uyha/tree-sitter-cmake")
            (c "https://github.com/tree-sitter/tree-sitter-c")
            (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
            (css "https://github.com/tree-sitter/tree-sitter-css")
            (elisp "https://github.com/Wilfred/tree-sitter-elisp")
            (gdscript "https://github.com/PrestonKnopp/tree-sitter-gdscript")
            (go "https://github.com/tree-sitter/tree-sitter-go")
            (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
            (html "https://github.com/tree-sitter/tree-sitter-html")
            (hyprlang "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang")
            (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
            (json "https://github.com/tree-sitter/tree-sitter-json")
            (make "https://github.com/alemuller/tree-sitter-make")
            (markdown "https://github.com/ikatyang/tree-sitter-markdown")
            (python "https://github.com/tree-sitter/tree-sitter-python")
            (rust "https://github.com/tree-sitter/tree-sitter-rust")
            (toml "https://github.com/tree-sitter/tree-sitter-toml")
            (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
            (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
            (vue "https://github.com/ikatyang/tree-sitter-vue")
            (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

    (defun start/install-treesit-grammars ()
      "Install missing treesitter grammars"
      (interactive)
      (dolist (grammar treesit-language-source-alist)
        (let ((lang (car grammar)))
          (unless (treesit-language-available-p lang)
            (treesit-install-language-grammar lang)))))

    ;; Call this function to install missing grammars
    (add-hook 'after-init-hook #'start/install-treesit-grammars)

    ;; Optionally, add any additional mode remappings not covered by defaults
    (setq major-mode-remap-alist
          '((yaml-mode . yaml-ts-mode)
            (sh-mode . bash-ts-mode)
            (c-mode . c-ts-mode)
            (c++-mode . c++-ts-mode)
            (css-mode . css-ts-mode)
            (python-mode . python-ts-mode)
            (mhtml-mode . html-ts-mode)
            (javascript-mode . js-ts-mode)
            (js-json-mode . json-ts-mode)
            (typescript-mode . typescript-ts-mode)
            (conf-toml-mode . toml-ts-mode)
            (gdscript-mode . gdscript-ts-mode)
            ))
    (setq treesit-font-lock-level 3)

    ;; Or if there is no built in mode
    (use-package cmake-ts-mode :ensure nil :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'"))
    (use-package go-mod-ts-mode :ensure nil :mode "\\.mod\\'")
    (use-package lua-ts-mode :ensure nil :mode "\\.lua\\'")
    (use-package rust-ts-mode :ensure nil :mode "\\.rs\\'")
    (use-package typescript-ts-mode :ensure nil :mode "\\.ts\\'")
    (use-package tsx-ts-mode :ensure nil :mode "\\.tsx\\'")
    (use-package yaml-ts-mode :ensure nil :mode ("\\.yaml\\'" "\\.yml\\'"))
#+end_src

*** Writing your own syntax highlight with treesitter
You can easily write your own font locking with treesitter

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
  ;; https://github.com/emacs-mirror/emacs/blob/master/admin/notes/tree-sitter/starter-guide
  (use-package go-ts-mode
    :ensure nil
    :mode "\\.go\\'"
    :config
    (defvar start/ts-font-lock-settings
      (treesit-font-lock-rules
       :language 'go ;; What language
       :feature 'function-highlight ;; A unique feature name that we can toggle.
       `(
         ;; Function calls
         (call_expression
          function: (selector_expression
                     field: (field_identifier) @font-lock-function-call-face)) ;; Use 'describe-face' to find faces
         ;; Property values
         (argument_list
          (selector_expression
           field: (field_identifier) @font-lock-property-use-face))
         (expression_list
          (selector_expression
           field: (field_identifier) @font-lock-property-use-face))
         ;; ((Treesit patern) @defface_Settings)
         ))
      "Go-ts-mode settings, fix not highlighting function calls and property values")

    (add-hook 'go-ts-mode-hook
              (lambda () (setq-local treesit-font-lock-settings
                                     (append treesit-font-lock-settings
                                             start/ts-font-lock-settings))))
    )
#+end_src
** Snippets (Yasnippet + Snippy)
*** Yasnippet
A template system for Emacs. And yasnippet-snippets is a snippet collection package.
To use it write out the full keyword (or use autocompletion) and press Tab.
*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
  (use-package yasnippet
    :hook (prog-mode . yas-minor-mode))

  (use-package yasnippet-snippets :defer)

  (defun start/corfu-yas-tab-handler ()
    "Prioritize corfu over yasnippet when yasnippet is active"
    (interactive)
    ;; There is no direct way to get if corfu is currently displayed so we watch the completion index
    (if (> corfu--index -1)
        (corfu-complete)
      (yas-next-field-or-maybe-expand)
      ))
  (use-package emacs
    :after (yasnippet corfu)
    :bind
    (:map yas-keymap
        ("TAB" . start/corfu-yas-tab-handler)
        ("RET" . nil)
        ("return" . nil)))
#+end_src

*** Snippy
VSCode/LSP snippet support for Emacs with Yasnippet.
Uses friendly snippets.
Developed by me.
Note: If you want to use a different package manager you need to change :vc(url ..) part.

*To use it, remove :tangle no from the beginning of the source code block.*
#+begin_src emacs-lisp :tangle no
    (use-package snippy
      :vc (:url "https://github.com/MiniApollo/snippy.git"
                :branch "main"
                :rev :newest)
      :hook (after-init . global-snippy-minor-mode)
      :custom
      (snippy-global-languages '("global")) ;; Recomended
      ;; Optional
      ;; (snippy-install-dir (expand-file-name <Your location>))
      ;; Use different snippet collections
      ;; (snippy-source '("Your git repo" . "my-snippets-dir"))
      :config
      (snippy-install-or-update-snippets)) ;; Autoupdate git repo
#+end_src
